version: "3"
dotenv: ["api-system/.env"]
includes:
  api:
    taskfile: ./api-system/taskfile.yml
    dir: ./api-system
  ui:
    taskfile: ./console/taskfile.yml
    dir: ./console

tasks:
  dev:
    silent: false
    cmds:
      - task api:dev &
      - task ui:dev

  build:
    deps:
      - api:build
      - ui:build

  prod:
    deps:
      - api:prod
  install:
    deps:
      - api:install
      - ui:install

  docker-compose:
    cmds:
      - docker compose --env-file ./api-system/.env up -d

  docker-compose-down:
    cmds:
      - docker compose down

  docker-compose-restart:
    cmds:
      - docker compose down
      - docker compose --env-file ./api-system/.env up -d

  docker-compose-logs:
    cmds:
      - docker compose logs -f
